//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int ID { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public decimal IDENTIFICACION { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
    }
}
